### ISSUE TITLE
how to keep it 24/7

### ISSUE THREAD

**Issue by junkie12** [RELIHR/Discord-Status-Rotator#5]
nice work but how do i keep it 24/7. thanks

**Comment by RELIHR** [comment]
> nice work but how do i keep it 24/7. thanks 

I guess in a host or not

**Comment by WHITESOUL123456** [comment]
Can it run in a host 24/7

**Comment by zeescaofg** [comment]
use https;//bot-hosting.net

**Comment by Exavierqq** [comment]
you could use flask application that hosted by your pc to keep it running! js lmk im sure i could implement it!
